name: Test

on:
  push:
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      is_upgraded: ${{ steps.step1.outputs.is_upgraded }}
      #current_version: ${{ steps.step1.outputs.current_version }}
      package_version: ${{ steps.step1.outputs.package_version }}
    steps:
      - uses: thieryw/check-version-upgrade@v1.0.0
        with:
         repo_name: gitlanding 
         repo_owner: thieryw
         branch: f1fd26aebfa290946ad872773681252f8c903073
        id: "step1"

  test2:
    runs-on: ubuntu-latest
    needs: test
    env:
      #IS_UPGRADED: ${{ needs.test.outputs.is_upgraded }}
      #CURRENT_VERSION: ${{ needs.test.outputs.current_version }}
      PACKAGE_VERSION: ${{ needs.test.outputs.package_version }}
    steps:
     - uses: actions/checkout@v2
     - run: echo $PACKAGE_VERSION